config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'dashboard#index'

  get 'up' => 'rails/health#show', :as => :rails_health_check
  get 'metrics' => 'metrics#index', :as => :metrics
  get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  get 'dashboard/monthly_overview', to: 'dashboard#monthly_overview', as: 'monthly_overview'

  resources :budgets do
    collection do
      post :copy_yearly_budgets
      get :import_form
      post :import
      post :import_preview
    end
  end

  resources :goals do
    member do
      patch :archive
      patch :unarchive
    end
  end

  resources :categories do
    resources :subcategories, controller: 'categories'
    member do
      get :average_spending
    end
  end
  get 'categories/:id/destroy', to: 'categories#destroy_confirm', as: 'destroy_category'

  resources :transactions do
    collection do
      get :import_form
      post :import
      post :import_preview
    end
  end

  resources :loans

  resources :loan_payments

  namespace :tools do
    get "import-export", to: "import_exports#show", as: :import_export
    post "import-export/export", to: "import_exports#export", as: :import_export_export
    post "import-export/import", to: "import_exports#import", as: :import_export_import
  end

  get "tools/amortization", to: "tools/calculators#amortization", as: "amortization_calculator"
  get "tools/investment", to: "tools/calculators#investment", as: "investment_calculator"
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  include Import

  GROUP_BY_OPTIONS = ['year & category', 'month & category', 'year', 'month'].freeze

  def index
    @selected_year = params[:year]&.to_i || Date.current.year
    @selected_month = params[:month].presence&.to_i
    @selected_category = params[:category].presence&.to_i
    @selected_source = params[:source].presence
    @selected_group_by = params[:group_by] || GROUP_BY_OPTIONS[0]
    @group_by_options = GROUP_BY_OPTIONS

    @available_years = Transaction.distinct.pluck(:date).map { |date| date.year }.uniq.sort.reverse
    @available_sources = Transaction.distinct.pluck(:import_source).sort

    year_range = Date.new(@selected_year, 1, 1)..Date.new(@selected_year, 12, 31)
    @transactions = Transaction.where(date: year_range)
                               .includes(:category)
                               .order(:date)

    if @selected_month.present?
      month_start = Date.new(@selected_year, @selected_month, 1)
      month_range = month_start..month_start.end_of_month
      @transactions = @transactions.where(date: month_range)
    end

    if @selected_category.present?
      @transactions = @transactions.where(category_id: @selected_category)
    end

    if @selected_source.present?
      @transactions = @transactions.where(import_source: @selected_source)
    end

    # Group transactions by selected group_by option
    if @selected_group_by.include?('month')
      @grouped_transactions = @transactions.group_by { |t| t.date.beginning_of_month }
    else
      @grouped_transactions = @transactions.group_by { |t| t.date.year }
    end

    if @selected_group_by.include?('category')
      @grouped_transactions.each do |date, transactions|
        @grouped_transactions[date] = transactions.group_by(&:category)
      end
    end

    @categories = Category.all.order(:name)
  end

  def show
    @transaction = Transaction.find(params[:id])
    @return_to = safe_return_to
  end

  def new
    @transaction = Transaction.new(any_params)
    @transaction.date = @transaction.date.presence || Date.today
    @categories = Category.all.order(:name)
    @return_to = safe_return_to
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.amount = (params[:transaction][:amount_dollars].to_f * 100).round
    @transaction.description = @transaction.description.presence || @transaction.category.name

    if @transaction.description.start_with?('Contribution to')
      @transaction.import_source = 'Goal Contribution'
    else
      @transaction.import_source = 'Manual'
    end

    if @transaction.save
      redirect_to filtered_return_to_path(@transaction), notice: 'Transaction was successfully created.'
    else
      @categories = Category.all.order(:name)
      flash[:model_errors] = @transaction.errors.full_messages
      redirect_to new_transaction_path(return_to: safe_return_to)
    end
  end

  def edit
    @transaction = Transaction.find(params[:id])
    @categories = Category.all.order(:name)
    @return_to = safe_return_to
  end

  def update
    @transaction = Transaction.find(params[:id])
    @transaction.amount = (params[:transaction][:amount_dollars].to_f * 100).round
    if @transaction.update(transaction_params)
      redirect_to return_to_path, notice: 'Transaction was successfully updated.'
    else
      @categories = Category.all.order(:name)
      @return_to = safe_return_to
      render :edit
    end
  end

  def destroy
    @transaction = Transaction.find(params[:id])
    if @transaction.destroy
      redirect_to return_to_path, notice: 'Transaction was successfully deleted.'
    else
      flash[:model_errors] = @transaction.errors.full_messages
      redirect_to return_to_path
    end
  end

  def import_form
  end

  def import_preview
    file = params[:file]

    if file.nil?
      flash.now[:alert] = "Please select a file to upload."
      render turbo_stream: turbo_stream.replace("flash_messages", partial: "layouts/flash_messages")
      return
    end

    begin
      service = ImportServiceLoader.service_for_file(file, Transaction)
      
      if service.present?
        @preview_data = service.preview
        @import_service_name = service.class.name.demodulize
                                      .sub(/^ImportTransactions/, '')
                                      .sub(/Service$/, '')
                                      .underscore
                                      .humanize
                                      .titleize
      else
        flash.now[:alert] = "The file does not appear to be valid for import."
        render turbo_stream: turbo_stream.replace("flash_messages", partial: "layouts/flash_messages")
        return
      end

      if @preview_data.empty?
        Rails.logger.info("No importable data found in the file.")
        flash.now[:alert] = "No importable data found in the file."
        render turbo_stream: turbo_stream.replace("flash_messages", partial: "layouts/flash_messages")
        return
      end
    rescue Errors::InvalidFileError => err
      flash.now[:alert] = err.message
      render turbo_stream: turbo_stream.replace("flash_messages", partial: "layouts/flash_messages")
      return
    rescue StandardError => err
      raise err
      flash.now[:alert] = "An error occurred while processing the file. Please try again."
      render turbo_stream: turbo_stream.replace("flash_messages", partial: "layouts/flash_messages")
      return
    end

    if @preview_data[:items].empty?
      flash.now[:alert] = "No transactions found for import."
      render turbo_stream: turbo_stream.replace("flash_messages", partial: "layouts/flash_messages")
      return
    end

    @categories = (Category.all.order(:name) + @preview_data[:new_categories]).sort_by(&:name)

    respond_to do |format|
      format.turbo_stream
    end
  end

  def import
    if params[:selected_transactions].nil?
      redirect_to import_form_transactions_path, alert: "No transactions selected to import."
      return
    end

    selected_transactions = params[:selected_transactions].map { |t| JSON.parse(t) }
    import_source = params[:import_service].presence || "Unknown Import"
    import_selected_transactions(selected_transactions, import_source)
    redirect_to transactions_path, notice: "Transactions imported successfully."
  end

  private

  def import_selected_transactions(selected_transactions, import_source = "Existing")
    extracted_categories = selected_transactions.map { |b| b['category'] }
    selected_transactions.each do |transaction_data|
      unique_id = transaction_data['unique_id']
      category_name = params["transaction_category_#{unique_id}"]
      
      # If a category was not originally found in the file, it will not have a category_type
      # (ie: if something was changed to an existing category). In that case we just find by name.
      extracted_category = extracted_categories.find { |c| c['name'] == category_name }

      category = if extracted_category
        Category.find_or_create_by(
          name: category_name,
          category_type: extracted_category['category_type']
        )
      else
        Category.find_or_create_by(name: category_name)
      end

      Transaction.create!(
        category: category,
        date: transaction_data['date'],
        amount: transaction_data['amount'],
        description: transaction_data['description'],
        import_source: import_source,
      )
    end
  end

  def transaction_params
    params.require(:transaction).permit(:category_id, :date, :description)
  end

  def any_params
    params.permit(:category_id, :date, :description)
  end

  def safe_return_to
    return_to = params[:return_to].to_s
    return_to = nil unless return_to.start_with?('/') && !return_to.start_with?('//')
    return_to.presence
  end

  def return_to_path
    safe_return_to || transactions_path
  end

  def filtered_return_to_path(transaction)
    return transactions_path(category: transaction.category_id, year: transaction.date.year) if safe_return_to.blank?

    uri = URI.parse(safe_return_to)
    return transactions_path(category: transaction.category_id, year: transaction.date.year) unless uri.path == transactions_path

    params = Rack::Utils.parse_nested_query(uri.query)
    params["category"] = transaction.category_id
    params["year"] = transaction.date.year if params["year"].blank?

    query = params.to_query
    query.present? ? "#{uri.path}?#{query}" : uri.path
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def status_class(status)
    case status
    when :new
      'text-bg-success'
    when :potential_duplicate
      'text-bg-danger'
    when :duplicate
      'text-bg-warning'
    when :ignored
      'text-bg-secondary'
    else
      'text-bg-secondary'
    end
  end

  def transaction_source_badge(transaction)
    source = transaction.import_source
    badge_class, icon_class = case source
                              when 'Manual'
                                ['bg-secondary', 'bi-pencil-fill']
                              when 'Goal Contribution'
                                ['bg-info text-dark', 'bi-bullseye']
                              when 'Loan Payment'
                                ['bg-primary', 'bi-bank']
                              else
                                # Assuming everything else is an import service
                                ['bg-light text-dark border', 'bi-cloud-upload']
                              end

    tag.span(class: "badge #{badge_class} d-inline-flex align-items-center gap-1", title: source, data: { bs_toggle: "tooltip" }) do
      concat tag.i(class: "bi #{icon_class}")
      concat span_text_for_source(source)
    end
  end

  def transaction_type_totals(transactions)
    totals = { income: 0.0, expense: 0.0, savings: 0.0 }
    transactions.each do |transaction|
      type_key = transaction.transaction_type.to_sym
      next unless totals.key?(type_key)

      totals[type_key] += transaction.amount_dollars
    end
    totals
  end

  private

  def span_text_for_source(source)
    source
  end
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true, html: { class: 'form-horizontal', data: { controller: 'form', action: 'submit->form#submit' } }) do |form| %>
  <% if @return_to.present? %>
    <%= hidden_field_tag :return_to, @return_to %>
  <% end %>
  <% category_input_id = "#{form.object_name}_category_id" %>
  <div class="mb-3" data-controller="select-filter">
    <div class="form-floating">
      <input type="text" class="form-control" placeholder="Category" id="<%= category_input_id %>" data-select-filter-target="input" data-action="input->select-filter#filter keydown->select-filter#handleKeydown focus->select-filter#openDropdown blur->select-filter#closeDropdown" />
      <%= form.collection_select :category_id, @categories, :id, :name, { include_blank: true }, { class: 'form-select d-none', id: "#{category_input_id}_select", data: { select_filter_target: "select", action: "change->select-filter#syncInput" } } %>
      <%= form.label :category_id, "Category", for: category_input_id %>
    </div>
  </div>

  <div class="form-floating mb-3">
    <%= form.text_field :date, class: "form-control", placeholder: "Date", data: { controller: "datepicker", datepicker_type_value: "day" } %>
    <%= form.label :date, "Date" %>
  </div>

  <div class="form-floating mb-3">
    <%= form.text_field :description, class: 'form-control', placeholder: "Description" %>
    <%= form.label :description, "Description" %>
  </div>

  <div class="input-group mb-3">
    <span class="input-group-text">$</span>
    <div class="form-floating">
      <%= form.text_field :amount_dollars, class: 'form-control', placeholder: "Amount", data: { type: 'number', controller: 'number-input', action: 'blur->number-input#format' } %>
      <%= form.label :amount_dollars, "Amount" %>
    </div>
  </div>

  <div class="text-end">
    <% if @return_to.present? %>
      <%= link_to @return_to, class: "btn btn-secondary" do %>
        <i class="bi bi-arrow-left"></i> Back
      <% end %>
    <% else %>
      <button type="button" class="btn btn-secondary" onclick="history.back()">
        <i class="bi bi-arrow-left"></i> Back
      </button>
    <% end %>
    <button type="submit" class="btn btn-primary">
      <i class="bi bi-check-lg"></i> <%= transaction.persisted? ? "Update" : "Create" %>
    </button>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card shadow">
        <div class="card-header h4 fw-bold">
          Edit Transaction
        </div>
        <div class="card-body">
          <%= render 'form', transaction: @transaction %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/transactions/import_form.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card shadow">
        <div class="card-header h4 fw-bold">
          Import Transactions
        </div>
        <div class="card-body">
          <%= turbo_frame_tag "import_preview" do %>
            <%= form_with url: import_preview_transactions_path, local: true, multipart: true do |form| %>
              <div class="mb-3">
                <%= form.label :file, "Select File", class: "form-label" %>
                <%= form.file_field :file, class: "form-control" %>
              </div>
              <div class="text-end">
                <button type="button" class="btn btn-secondary" onclick="history.back()">
                  <i class="bi bi-arrow-left"></i> Back
                </button>
                <button type="submit" class="btn btn-primary">
                  <i class="bi bi-upload"></i> Preview Import
                </button>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  function toggleSelectAll(month, selectAll) {
    const checkboxes = document.querySelectorAll(`#transactions-${month} .transaction-checkbox`);
    checkboxes.forEach(checkbox => {
      checkbox.checked = selectAll;
    });
  }
</script>

app/views/transactions/import_preview.turbo_stream.erb
<%= turbo_stream.replace "import_preview" do %>
  <div>
    <%= form_with url: import_transactions_path, local: true do |form| %>
      <%= hidden_field_tag :import_service, @import_service_name %>
      <% if @preview_data[:new_categories].present? %>
        <div class="alert alert-info mb-3">
          <h5 class="alert-heading"><i class="bi bi-info-circle me-2"></i>Expense Categories to Create</h5>
          <div class="d-flex flex-wrap gap-2">
            <% @preview_data[:new_categories].each do |category| %>
              <span class="badge bg-primary"><%= category.name %></span>
            <% end %>
          </div>
        </div>
      <% end %>

      <div class="mb-4">
        <% @preview_data[:items].group_by { |t| t[:date].beginning_of_month }.each_with_index do |(month, transactions_by_month), month_index| %>
          <div class="d-flex justify-content-between align-items-center mb-2 mt-4">
            <h5 class="m-0">Transactions for <%= month.strftime("%B %Y") %></h5>
            <div class="btn-group btn-group-sm">
              <button type="button" class="btn btn-outline-secondary" onclick="toggleSelectAll('<%= month_index %>', true)">Select All</button>
              <button type="button" class="btn btn-outline-secondary" onclick="toggleSelectAll('<%= month_index %>', false)">Select None</button>
            </div>
          </div>
          <div class="table-responsive">
            <table class="table table-bordered table-hover align-middle">
              <thead class="table-light">
                <tr>
                  <th class="text-center" style="width: 50px;">Select</th>
                  <th>Date</th>
                  <th>Description</th>
                  <th>Amount</th>
                  <th>Category</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody id="transactions-<%= month_index %>">
                <% transactions_by_month.each_with_index do |transaction, transaction_index| %>
                  <tr>
                    <td class="text-center">
                      <%= check_box_tag "selected_transactions[]", transaction.to_json, transaction[:status] == :new, class: "transaction-checkbox form-check-input" %>
                    </td>
                    <td><%= transaction[:date].strftime("%d %B %Y") %></td>
                    <td><%= transaction[:description] %></td>
                    <td><%= number_to_currency(transaction[:amount] / 100.0) %></td>
                  <td>
                    <% category_input_id = "transaction_category_#{transaction[:unique_id]}" %>
                    <div data-controller="select-filter">
                      <input type="text" class="form-control form-control-sm mb-1" placeholder="Category" id="<%= category_input_id %>" data-select-filter-target="input" data-action="input->select-filter#filter keydown->select-filter#handleKeydown focus->select-filter#openDropdown blur->select-filter#closeDropdown" />
                      <%= select_tag category_input_id,
                        options_for_select(@categories.map { |c| ["#{c.name}#{c.new_record? ? ' (new)' : ''}", c.name] }, transaction[:category].name),
                        id: "#{category_input_id}_select", class: "form-select form-select-sm d-none", data: { select_filter_target: "select", action: "change->select-filter#syncInput" } %>
                    </div>
                  </td>
                    <td>
                      <span class="badge <%= status_class(transaction[:status]) %>">
                        <%= transaction[:status].to_s.humanize %>
                      </span>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        <% end %>
      </div>

      <div class="text-end">
        <%= button_tag type: 'submit', class: "btn btn-success" do %>
          <i class="bi bi-check-lg me-1"></i> Import Selected
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/transactions/new.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card shadow">
        <div class="card-header h4 fw-bold">
          New Transaction
        </div>
        <div class="card-body">
          <%= render 'form', transaction: @transaction %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/transactions/show.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card mb-4">
        <div class="card-header h4 d-flex justify-content-between align-items-center">
          <div class="d-flex align-items-center">
            <% if @return_to.present? %>
              <%= link_to @return_to, class: "btn btn-link text-body p-0 me-3 text-decoration-none", data: { controller: "tooltip", bs_toggle: "tooltip" }, title: "Back" do %>
                <i class="bi bi-arrow-left"></i>
              <% end %>
            <% else %>
              <button type="button" class="btn btn-link text-body p-0 me-3 text-decoration-none" onclick="history.back()" data-controller="tooltip" data-bs-toggle="tooltip" title="Back">
                <i class="bi bi-arrow-left"></i>
              </button>
            <% end %>
            Transaction Details
          </div>
          <div class="d-flex align-items-center gap-2">
            <% if @transaction.loan_payment.present? %>
              <button class="btn btn-sm btn-primary" disabled title="Cannot edit loan payment transaction" data-controller="tooltip" data-bs-toggle="tooltip">
                <i class="bi bi-pencil"></i>
              </button>
              <button class="btn btn-sm btn-danger" disabled title="Cannot delete loan payment transaction. Please use the Loan Payments page." data-controller="tooltip" data-bs-toggle="tooltip">
                <i class="bi bi-trash"></i>
              </button>
            <% else %>
              <%= link_to edit_transaction_path(@transaction, return_to: @return_to), class: 'btn btn-sm btn-warning', title: 'Edit', data: { controller: 'tooltip', bs_toggle: 'tooltip' } do %>
                <i class="bi bi-pencil"></i>
              <% end %>
              <%= link_to transaction_path(@transaction, return_to: @return_to), title: 'Delete', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?', controller: 'tooltip', bs_toggle: 'tooltip' }, class: 'btn btn-sm btn-danger' do %>
                <i class="bi bi-trash"></i>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="card-body">
          <div class="d-flex align-items-center mb-4">
            <span class="text-muted text-uppercase small fw-bold me-3">Category</span>
            <span class="badge rounded-pill bg-light text-dark border px-3 py-2 shadow-sm">
              <i class="bi bi-tag-fill me-2 text-primary"></i><%= @transaction.category.name %>
            </span>
          </div>

          <div class="row g-3 mb-4">
            <div class="col-md-4">
              <div class="p-3 border rounded bg-light text-center h-100">
                <div class="text-muted small text-uppercase fw-bold mb-1">Type</div>
                <div class="h4 mb-0"><%= @transaction.category.category_type.humanize.titleize %></div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="p-3 border rounded bg-light text-center h-100">
                <div class="text-muted small text-uppercase fw-bold mb-1">Date</div>
                <div class="h4 mb-0"><%= @transaction.date.strftime("%B %d, %Y") %></div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="p-3 border rounded bg-light text-center h-100">
                <div class="text-muted small text-uppercase fw-bold mb-1">Amount</div>
                <div class="h4 mb-0 text-primary"><%= number_to_currency(@transaction.amount / 100.0) %></div>
              </div>
            </div>
          </div>

          <div class="mb-4">
            <h5 class="card-title">Details</h5>
            <ul class="list-group list-group-flush">
              <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                <span class="text-muted">Description</span>
                <span class="fw-bold"><%= @transaction.description %></span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                <span class="text-muted">Source</span>
                <span><%= transaction_source_badge(@transaction) %></span>
              </li>
            </ul>
          </div>
          
          <% if @transaction.loan_payment.present? %>
            <div class="card bg-light border-0">
              <div class="card-body">
                <h5 class="card-title mb-3"><i class="bi bi-bank me-2"></i>Associated Loan Payment</h5>
                <div class="row g-3">
                  <div class="col-md-6">
                    <small class="text-muted d-block">Loan</small>
                    <%= link_to @transaction.loan_payment.loan.loan_name, loan_path(@transaction.loan_payment.loan), class: 'fw-bold text-decoration-none' %>
                  </div>
                  <div class="col-md-6">
                    <small class="text-muted d-block">Payment Date</small>
                    <span class="fw-bold"><%= @transaction.loan_payment.payment_date.strftime("%B %d, %Y") %></span>
                  </div>
                  <div class="col-md-4">
                    <small class="text-muted d-block">Paid Amount</small>
                    <span class="fw-bold"><%= number_to_currency(@transaction.loan_payment.paid_amount / 100.0) %></span>
                  </div>
                  <div class="col-md-4">
                    <small class="text-muted d-block">Principal</small>
                    <span class="fw-bold text-success"><%= number_to_currency((@transaction.loan_payment.paid_amount - @transaction.loan_payment.interest_amount) / 100.0) %></span>
                  </div>
                  <div class="col-md-4">
                    <small class="text-muted d-block">Interest</small>
                    <span class="fw-bold text-warning"><%= number_to_currency(@transaction.loan_payment.interest_amount / 100.0) %></span>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>